# Generated by Django 3.0.7 on 2020-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagin_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Картинка на прокрутке',
                'verbose_name_plural': 'Картинки на прокрутке',
            },
        ),
        migrations.AlterModelOptions(
            name='abou',
            options={'verbose_name': 'Про сайт', 'verbose_name_plural': 'Про сайт'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
    ]
