# Generated by Django 3.0.7 on 2020-07-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200709_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagin',
            name='batn_url',
            field=models.URLField(default='aa', verbose_name='Адреса для кнопки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagin',
            name='texte',
            field=models.TextField(default='dssa', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagin',
            name='title',
            field=models.TextField(default='ds/', verbose_name='Назва'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abou',
            name='about_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='imagin',
            name='imagin_url',
            field=models.URLField(verbose_name='адреса картинки'),
        ),
    ]
