# Generated by Django 3.0.7 on 2020-07-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200709_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagin',
            name='bath_title',
            field=models.TextField(default='1', verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
    ]
