# Generated by Django 3.0.7 on 2020-07-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_topx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer', models.FileField(upload_to='media/files')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagin',
            options={'verbose_name': 'Картинка на прокрутці', 'verbose_name_plural': 'Картинки на прокруці'},
        ),
        migrations.AlterModelOptions(
            name='topx',
            options={'verbose_name': 'Стаття на головній', 'verbose_name_plural': 'Статті на головній'},
        ),
    ]
