# Generated by Django 3.0.7 on 2020-07-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200709_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downl',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файли'},
        ),
        migrations.AlterField(
            model_name='downl',
            name='filer',
            field=models.FileField(upload_to='files'),
        ),
    ]
