# Generated by Django 3.0.7 on 2020-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagin1',
            field=models.ImageField(upload_to='articles/', verbose_name='Картинка 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imagin2',
            field=models.ImageField(blank=True, upload_to='articles/', verbose_name='Картинка 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imagin3',
            field=models.ImageField(blank=True, upload_to='articles/', verbose_name='Картинка 3'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
    ]
